### ISSUE TITLE
[change] Possibilitar adição de endereço da empresa após criação da mesma

### ISSUE THREAD

**Issue by tadeubdev** [valdiney/zig#107]
História: Ficou perdida após criar a empresa, foi direto para pedidos, ou seja, o ato de criação de endereços após criação da empresa não é intuitivo. Possíveis soluções: inserir o cadastro de um endereço direto no cadastro da empresa; inserir um botão dentro do cadastro de empresa que já o leva para o cadastro de endereços.

- [x] Possibilitar adicionar endereço da empresa após criação da mesma

**Comment by valdiney** [comment]
No momento, coloquei uma mensagem para que os usuários leiam e saibam que precisam cadastrar o endereço para trabalhar com o modulo de pedidos.
