### ISSUE TITLE
[feature] Possibilitar ao usuário criar segmentos da empresa

### ISSUE THREAD

**Issue by tadeubdev** [valdiney/zig#108]
Campo de segmento da empresa é mais importante do que pensávamos, ele precisa ser especificado, possíveis soluções: liberar o campo para digitação ou então liberar uma parte no sistema aonde a pessoa pode cadastrar o segmento.

- [ ] Na área de cadastro de clientes (/clientes > adicionar novo), abaixo do select de segmento, adicionar link: criar novo segmento. Ou ainda adicionar um botão com um (+) ao lado do select.
- [ ] Quando clicado, abrirá um novo modal aonde ele poderá criar um novo segmento.
- [ ] Quando o usuário clicar em salvar segmento, o novo segmente será adicionado ao select.

**Comment by valdiney** [comment]
Foi implementado mais opções de segmentos
