### ISSUE TITLE
[bug]: Corrigir erro na sessão do usuário

### ISSUE THREAD

**Issue by tadeubdev** [valdiney/zig#112]
A sessão está sendo perdida em algum momento.
Quando o usuário está conectado pelo celular, ele não fica nem uma hora.

**Comment by tadeubdev** [comment]
Isso tá dando problema ainda? Não lembro...

**Comment by tadeubdev** [comment]
@valdiney

**Comment by valdiney** [comment]
Iai man, na verdade não! Tá batendo certo! Por isso fechei a issue!

**Comment by tadeubdev** [comment]
assim, kk entendi
