### ISSUE TITLE
Sistema não carrega após login

### ISSUE THREAD

**Issue by fernandollira** [valdiney/zig#113]
Boa noite.
Instalei o sistema em um vps linux, coloco o usuario de teste mas nao carrega a pagina home, ela fica em branco!
Ficarei grato pela solução.
Abraços!!!

**Comment by valdiney** [comment]
Olá Fernando, estaremos dando uma olhada nesse problema e assim que identificado, daremos um feedback! Muito obrigado pela contribuição!

**Comment by valdiney** [comment]
Prontinho, acabei de subir uma correção! Tu pode dar um pull no projeto e tentar novamente?

**Comment by fernandollira** [comment]
Obrigado Valdiney pelo suporte, vou dar um pull agora mesmo no projeto e
aviso como ficou ok?
Muito obrigado pela atenção e gostaria de contribuir nesse projeto de
alguma forma não tenho muita afinidade com o laravel, mas irei me
empenhar em aprender eu desenvolvo mais pra dispositivos móveis. Grande
abraço!!!


Em seg., 1 de mar. de 2021 às 18:45, Valdiney França <
notifications@github.com> escreveu:

**Comment by valdiney** [comment]
Tranquilo Fernando! Espero que dê tudo certo por ai! Na verdade não usamos Laravel, desenvolvemos um framework próprio baseado na interoperabilidade do composer! É bem simples na verdade!

**Comment by fernandollira** [comment]
Me desculpa te incomodar tanto Valdiney mas é porque estou empolgado pra
rodar essa seu sistema kkk, fiz um pull no projeto mas agora tenho esse
erro na base de dados em relação ao relatório de vendas no dia.

Desculpa está tomando seu tempo.

Em seg., 1 de mar. de 2021 às 20:15, Valdiney França <
notifications@github.com> escreveu:

**Comment by valdiney** [comment]
Fernando, coloca um print pra vermos o erro!

**Comment by fernandollira** [comment]
Bom dia Valdiney, coloco sim. Eu comentei uma linha do código especificado
no erro do print daí sumiu o erro e consegui logar
mas não mostra na página home as vendas realizadas no dia.
Mais uma vez obrigado.

Em ter., 2 de mar. de 2021 às 08:31, Valdiney França <
notifications@github.com> escreveu:

**Comment by valdiney** [comment]
Fernando, tu acessou o ambiente online com as credenciais que te passei? Lá você vai consegui visualizar melhor o sistema neste momento! Mas vou dar uma olhada depois nessa parte de não mostrar as vendas do dia! Ou não tem dados ou pode ser algo na query!

**Comment by fernandollira** [comment]
Olá Valdiney acho que é algum problema na query. Seu eu te passar os dados do meu vps teria como dar uma olhada lá? Pois ficaria mais fácil de encontrar o problema e postar a solução!!!

**Comment by fernandollira** [comment]
Olá Valdiney acho que é algum problema na query. Seu eu te passar os dados
do meu vps teria como dar uma olhada lá? Pois ficaria mais fácil de
encontrar o problema e postar a solução!!!


Abraços!

Em ter., 2 de mar. de 2021 às 08:47, Valdiney França <
notifications@github.com> escreveu:

**Comment by valdiney** [comment]
Fernando, vou me organizar para dar uma olhada nessa questão da query! Acho que eu realmente tinha visto isso mesmo em alguma instalação, mas no outro dia já estava mostrando os dados. Tente cadastrar mais dados em outros dias pra ver se mostra algo! Mas é um erro sim e vamos resolver com fé em Deus! Muito obrigado pelo feedback!

**Comment by valdiney** [comment]
Resolvido!
