### ISSUE TITLE
Pessoal alguém pode me ajudar a criar o meu usuário admin ? 

### ISSUE THREAD

**Issue by Seiteigr** [valdiney/zig#114]
O de teste não funciona e eu não consigo achar um jeito de inserir um nas tabelas sem bugar tudo kk

**Comment by Seiteigr** [comment]
Vacilo meu não vi a database de teste kk

**Comment by valdiney** [comment]
haha suave meu caro!

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus projetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no ***@***.***> )



________________________________
De: Seiteigr ***@***.***>
Enviado: domingo, 11 de abril de 2021 15:33
Para: valdiney/zig ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [valdiney/zig] Pessoal alguém pode me ajudar a criar o meu usuário admin ? (#114)


Vacilo meu não vi a database de teste kk

**Comment by valdiney** [comment]
tenta usar a senha: 32402709 como senha pra ver se vai!

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus projetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no ***@***.***> )



________________________________
De: Seiteigr ***@***.***>
Enviado: sexta-feira, 9 de abril de 2021 18:40
Para: valdiney/zig ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [valdiney/zig] Pessoal alguém pode me ajudar a criar o meu usuário admin ? (#114)


O de teste não funciona e eu não consigo achar um jeito de inserir um nas tabelas sem bugar tudo kk
