### ISSUE TITLE
Após logar estou com esse problema gente.

### ISSUE THREAD

**Issue by Seiteigr** [valdiney/zig#115]
****

Warning: PDO::query(): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'zig.vendas.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in C:\Users\Karamagod\Desktop\zig\System\NativeQuery\NativeQuery.php on line 15

Fatal error: Uncaught Error: Call to a member function execute() on bool in C:\Users\Karamagod\Desktop\zig\System\NativeQuery\NativeQuery.php:18 Stack trace: #0 C:\Users\Karamagod\Desktop\zig\App\Repositories\VendasRepository.php(66): System\NativeQuery\NativeQuery->query('SELECT DATE_FOR...') #1 C:\Users\Karamagod\Desktop\zig\App\Controllers\HomeController.php(63): App\Repositories\VendasRepository->quantidadeDeVendasRealizadasPorDia(Array, '1') #2 [internal function]: App\Controllers\HomeController->index() #3 C:\Users\Karamagod\Desktop\zig\System\Route\SelectController.php(228): call_user_func(Array) #4 C:\Users\Karamagod\Desktop\zig\System\Route\SelectController.php(63): System\Route\SelectController->instantiateController(Object(App\Controllers\HomeController), 'index', Array) #5 C:\Users\Karamagod\Desktop\zig\routes\routes.php(123): System\Route\SelectController->run() #6 C:\Users\Karamagod\Desktop\zig\index.php(43): require_once('C:\\Users\\Karama...') #7 {main} thrown in C:\Users\Karamagod\Desktop\zig\System\NativeQuery\NativeQuery.php on line 18
![image](https://user-images.githubusercontent.com/38665612/114316758-4c16a580-9adb-11eb-94f1-64f498a16598.png)

**Comment by cicerosnt** [comment]
qual a seria a resolução?
