### ISSUE TITLE
[HELP] Install Windows

### ISSUE THREAD

**Issue by Kakamanoel0** [valdiney/zig#116]
Teria como eu fazer uma instalação desse sistema em um Windows? utilizando um xampp ou algo do tipo?

**Comment by tadeubdev** [comment]
Olá @Kakamanoel0 , seja bem vindo!
Sim, você pode fazer a instalação normalmente no Windows.
Siga o passo a passo aqui: https://github.com/valdiney/zig/blob/master/docs/instalacao.md

**Comment by Kakamanoel0** [comment]
Desculpa a demora para responder, mais então, eu tentei fazer a instalação dele em um ambiente xampp. [url](https://www.apachefriends.org/pt_br/index.html)
tentei em uma versão nova, dês de uma mais antiga, porém não obtive resultado com nenhuma das duas.
Obtive os seguintes erros no php:

> Warning: getenv() expects exactly 1 parameter, 2 given in C:\xampp\htdocs\index.php on line 8

> Warning: getenv() expects exactly 1 parameter, 2 given in C:\xampp\htdocs\index.php on line 8

> Warning: require_once(C:\xampp\htdocs/vendor/autoload.php) [function.require-once]: failed to open stream: No such file or directory in C:\xampp\htdocs\index.php on line 16

> Fatal error: require_once() [function.require]: Failed opening required 'C:\xampp\htdocs/vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\index.php on line 16

Imagem do erro: [url](https://imgur.com/a/fKLOLqh)

**Comment by tadeubdev** [comment]
Olá @Kakamanoel0 , bom dia! Parece que tem um erro no arquivo do xampp.
Pode verificar, por favor, o que tem nesse arquivo na linha 8? `C:\xampp\htdocs\index.php`
