### ISSUE TITLE
Bug quando vai atualizar dados do usuário

### ISSUE THREAD

**Issue by thiagunix** [valdiney/zig#118]
Parabéns pelo sistema.
Muito bonito e intuitivo.

Quando você tenta alterar o dados usuário e não seleciona nenhum perfil o post vai a palavra "selecione..." e o banco se perde na hora de gravar e da erro segue o log.

[Wed Nov 03 18:35:55.475624 2021] [php7:warn] [pid 1076] [client 0.0.0.0:8856] PHP Warning:  PDOStatement::execute(): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'Selecione...' for column `zig`.`usuarios`.`id_perfil` at row 1 in /var/www/zig/System/NativeQuery/NativeQuery.php on line 116, referer: http://0.0.0.0/usuario

Muito Obrigado pela contribuição do projeto

**Comment by valdiney** [comment]
Olá @thiagunix, muito obrigado pelo retorno e contribuição! Darei uma olhadinha nesse modulo!

**Comment by valdiney** [comment]
@thiagunix acabei de subir uma correção com relação ao seu feedback!

**Comment by valdiney** [comment]
@thiagunix acabei de subir uma correção com relação ao seu feedback!
