### ISSUE TITLE
[Ajuda] Composer install

### ISSUE THREAD

**Issue by StrikOne** [valdiney/zig#119]
Olá, estou seguindo os passos para instalação e atualmente estou com este problema após ter instalado o composer, tentei alguns passos na internet mas não consegui resolver, alguém me indicar algo a fazer?

![composer](https://user-images.githubusercontent.com/17607306/148299206-a94bf932-8d2e-463e-9d77-bd7a71bffbad.png)

**Comment by tadeubdev** [comment]
Opa! Então, pelo que entendi você está utilizando a versão 8.1.1 do PHP, e o ZigMoney utiliza o PHP na versão 7.
Você conseguiria/poderia tentar voltar a versão do PHP para 7.3?
A gente poderia mudar ali, mas muitos outros pacotes que utilizamos também utiliza o PHP 7, vai serum pouco mais complicado atualizar... ( @valdiney dá uma olhada aqui, por favor)

**Comment by StrikOne** [comment]
Obrigado pela ajuda, resolvi voltando a versão para 7.3 e liberando as extensões fileinfo e gd2 em php.ini

**Comment by valdiney** [comment]
Que bom que resolveu o problema @StrikOne, qualquer duvida ou sugestões, fique a vontade para contribuir! @tadeubdev muito obrigado pelo help! Tu é o  cara!

**Comment by tadeubdev** [comment]
> Que bom que resolveu o problema @StrikOne, qualquer duvida ou sugestões, fique a vontade para contribuir! @tadeubdev muito obrigado pelo help! Tu é o cara!

Tamo junto!

**Comment by avenseElectro** [comment]
pk com o php 8.1 ao dá? eu nao queria fazer o dongrade do php

**Comment by valdiney** [comment]
Esta versao do zig esta desatualizada. Tem um repositorio com o sistema na versao 8.2, mas acho que deixou de ser opensource

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus p<https://github.com/valdiney>rojetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no ***@***.***> )


________________________________
De: avenseElectro ***@***.***>
Enviado: quarta-feira, 10 de julho de 2024 13:38
Para: valdiney/zig ***@***.***>
Cc: Valdiney França ***@***.***>; Mention ***@***.***>
Assunto: Re: [valdiney/zig] [Ajuda] Composer install (Issue #119)


pk com o php 8.1 ao dá? eu nao queria fazer o dongrade do php
