### ISSUE TITLE
(Dúvida) Atualizações para php 8

### ISSUE THREAD

**Issue by Kobukis** [valdiney/zig#125]
Pessoal, parabéns pelo projeto, estou testando aqui e vi que não estava funcionando com o php 8 eu estou aprendendo laravel e modifiquei o arquivo composer.json para aceitar o php8, ficou assim: 

{
    "name": "valdiney/vai",
    "description": "This is the zig project.",
    "type": "project",
    "license": "MIT",
    "authors": [
        {
            "name": "Valdiney França",
            "email": "valdiney.2@hotmail.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "App\\": "App/",
            "System\\": "System/",
            "Tests\\": "tests/"
        },
        "files": [
           "System/Helpers/simpleHelpers.php",
           "System/Helpers/dateHelper.php"
        ]
    },
    "minimum-stability": "stable",
    "require": {
        "php": "^8.0",
        "ext-zip": "*",
        "ext-gd": "*",
        "vlucas/phpdotenv": "^2.5",
        "phpoffice/phpspreadsheet": "^1.13",
        "symfony/symfony": "^5.1",
        "lcobucci/jwt": "^4.1.4",
        "dompdf/dompdf": "^1.1.1",
        "phpmailer/phpmailer": "^6.1",
        "picqer/php-barcode-generator": "^2.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.0.0"
    }
}

Agora estou com um problema, não consigo entrar no sistema pra testar com o usúario padrão inicial  e vi pelo phpmyadmin que não tem nenhum registro no banco, o que estou fazendo de errado? E porque não funciona o comando artisan e sim o "php command migrate"? 

Obrigado.

**Comment by tadeubdev** [comment]
Olá @Kobukis , bom dia! =D
Então, a primeira coisa é que o projeto ainda não dá suporte ao PHP 8... alguns dos pacotes que utilizamos no momento irão precisar de atualização para isso. O nosso conselho é que utilize o PHP na versão 7.2 - 7.4.
A segunda é que o projeto foi criado do zero, e não em Laravel. Por isso do comando `artisan` do Laravel não funcionar. O comando `php command` foi criado por nós para facilitar as migrations e as seeds do banco.

**Comment by Kobukis** [comment]
Oi @tadeubdev, bom dia! 
Entendi vou utilizar a versão 7.4. 
Obrigado sucesso!

**Comment by tadeubdev** [comment]
Estamos à disposição! :D
