### ISSUE TITLE
Problemas com a geração de Código de barras

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#129]
Fatal error: Uncaught Error: Call to undefined function generateRandomCodigoDeBarras() in C:\Sistemas\zig\.temps\preenche-codigo-de-barras-nos-produtos.php:9 Stack trace: #0 C:\Sistemas\zig\.temps\preenche-codigo-de-barras-nos-produtos.php(27): handleAdicionaCodigoNosProdutos() #1 C:\Sistemas\zig\index.php(44): include('C:\\Sistemas\\zig...') #2 {main} thrown in C:\Sistemas\zig\.temps\preenche-codigo-de-barras-nos-produtos.php on line 9

**Comment by tadeubdev** [comment]
mano, tenta dar um "composer dump" pra ver, por favor... eu alterei o composer.json, acho que é isso!

**Comment by valdiney** [comment]
Eu tinha feito antes, mas não funcionou! haha mas agora tá top;

**Comment by valdiney** [comment]
Tudo resolvido e na paz de Deus

**Comment by tadeubdev** [comment]
hehe muito bom!
