### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thexilipiz** [valdiney/zig#130]
fica dando esse erro

Warning: PDO::query(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'codigo' in 'where clause' in C:\xampp\htdocs\zig-master\System\NativeQuery\NativeQuery.php on line 16

Fatal error: Uncaught Error: Call to a member function execute() on bool in C:\xampp\htdocs\zig-master\System\NativeQuery\NativeQuery.php:19 Stack trace: #0 C:\xampp\htdocs\zig-master\.temps\preenche-codigo-de-barras-nos-produtos.php(20): System\NativeQuery\NativeQuery->query('SELECT id FROM ...') #1 C:\xampp\htdocs\zig-master\index.php(44): include('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\zig-master\public\index.php(3): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\zig-master\System\NativeQuery\NativeQuery.php on line 19

**Comment by valdiney** [comment]
Me parece que está faltando a coluna (codigo na tabela produtos). Cria esse campo codigo na tabela produtos. é um int de tamanho 11

**Comment by thexilipiz** [comment]
E esse erro? Deprecated: auto_detect_line_endings is deprecated in C:\xampp\htdocs\zig-master\vendor\vlucas\phpdotenv\src\Loader.php on line 172

**Comment by valdiney** [comment]
Qual versão do php você está usando? A maioria das libs do sistema funciona para php 7
