### ISSUE TITLE
Como instalar esse programa?

### ISSUE THREAD

**Issue by felipecesarl** [valdiney/zig#133]
Boa tarde! Sou meio leigo no assunto, pode me explicar como instalar passo a passo? Ou tem algum vídeo? Ele usa o Xampp?

**Comment by valdiney** [comment]
Olá Felipe, tudo bem? Realmente é necessário um pouco de conhecimento para instalar o sistema. Não é algo tão complexo, mas exige algumas configurações. Infelizmente no momento não temos nenhum video e nem postagem mostrando. Mas é algo que já está na lista de tarefas e assim que sobrar um tempinho faremos!

Ele pode ser usado com o xamp sim, desde que algumas configurações do php sejam atendidas. Uma delas é versão 7.4.8 do php.
Nós recomendamos utilizar o próprio servidor embutido que vem na instalação manual do php.

Se faz necessário ter o composer instalado na sua máquina! O composer é um gerenciador de dependencias do php. é usado para baixar as bibliotecas necessárias para o projeto!

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus projetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no ***@***.***> )


________________________________
De: felipecesarl ***@***.***>
Enviado: quarta-feira, 6 de abril de 2022 15:25
Para: valdiney/zig ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [valdiney/zig] Como instalar esse programa? (Issue #133)


Boa tarde! Sou meio leigo no assunto, pode me explicar como instalar passo a passo? Ou tem algum vídeo? Ele usa o Xampp?
