### ISSUE TITLE
Não Consigo instalar 

### ISSUE THREAD

**Issue by Igor-Montuani** [valdiney/zig#135]
Ao executar o comando php command migrate ele retorna a mensagem de erro 
PS C:\xampp\htdocs\zig> php command migrate
- cria tabela migrations
- cria tabela de clientes segmentos
- cria tabela de clientes tipos
- cria tabela de empresas
- cria tabela de clientes
- cria tabela de meios de pagamento
- cria tabela de tipos pdv
- cria tabela de clientes enderecos
- cria tabela de config pdv
- cria tabela de perfis
- cria tabela de sexos
- cria tabela de usuarios
- cria tabela de modulos de usuarios
- cria tabela de vendas
- cria tabela de logs
- campo email
- acriar campo id segmento em empresas
- chave estrageira de id segmento em tabela empresas
- cria tabela de recuperacao de senha
- adiciona coluna remember token na tabela usuarios
- adiciona coluna remember expire date na tabela usuarios
- cria tabela de pedidos
- cria tabela de produtos pedidos
- cria tabela situacoes pedidos
- adiciona coluna deleted at a tabela produtos
- lista de clientes segmentos
- adiciona boleto aos meios de pagamento
- adiciona data compensacao a tabela de vendas
- created at em vendas
- adiciona deleted at na tabela de usuarios
PHP Warning:  PDO::query(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'usuarios' in C:\xampp\htdocs\zig\System\NativeQuery\NativeQuery.php on line 16

Warning: PDO::query(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'usuarios' in C:\xampp\htdocs\zig\System\NativeQuery\NativeQuery.php on line 16
Tabelas migradas com sucesso! ;)

**Comment by Igor-Montuani** [comment]
E o navegador a mesma coisa 
Warning: require_once(C:\xampp\htdocs\zig/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\zig\index.php on line 16

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\zig/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\zig\index.php on line 16

**Comment by valdiney** [comment]
Tem uma pasta chama Dump, restaura o seu banco usando esse Dump. [dump.sql](https://github.com/valdiney/zig/blob/master/dump/dump.sql) creio que ele esteja mais atualizado do que as migrations

**Comment by Igor-Montuani** [comment]
Deu certo porém a senha do usuario não funciona que é 33473347

**Comment by valdiney** [comment]
@Igor-Montuani cara, vai na tabela de usuarios e edita o usuario [admin@admin.com](mailto:admin@admin.com), coloca essa senha lá.
3b5df72898847f008454f4ed60280d6bdffc890d

esse é o rash da senha 33473347

**Comment by Igor-Montuani** [comment]
Já fiz isso porém não deu certo

**Comment by valdiney** [comment]
Tu quer fazer uma chama rapida no google meet?

**Comment by Igor-Montuani** [comment]
Opa só mandar o link

**Comment by valdiney** [comment]
https://meet.google.com/xvp-wbdr-dws

**Comment by valdiney** [comment]
Resolvido!

**Comment by itsfks** [comment]
Olá! Estou com esse mesmo problema, qual foi o procedimento para a correção?
