### ISSUE TITLE
Erro durante a instalação.

### ISSUE THREAD

**Issue by itsfks** [valdiney/zig#136]
Olá, estou enfrentando alguns problemas durante a instalação do PDV. Vi que alguns colegas tiveram o mesmo problema (ou quase), porém não encontrei uma solução explícita para o problema. Gostaria de solicitar suporte/orientação para resolver o erro e prosseguir na implementação do mesmo.

Durante a instalação estava recebendo este erro:
`PHP Warning:  PDO::query(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'usuarios' in /home/felipe/zig/System/NativeQuery/NativeQuery.php on line 16`

Log da aplicação no servidor:
`[Mon Aug 15 23:32:57 2022] PHP Warning:  PDO::query(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'codigo' in 'where clause' in /home/felipe/zig/System/NativeQuery/NativeQuery.php on line 16
[Mon Aug 15 23:32:57 2022] PHP Fatal error:  Uncaught Error: Call to a member function execute() on bool in /home/felipe/zig/System/NativeQuery/NativeQuery.php:19
Stack trace:
#0 /home/felipe/zig/.temps/preenche-codigo-de-barras-nos-produtos.php(20): System\NativeQuery\NativeQuery->query()
#1 /home/felipe/zig/index.php(44): include('/home/felipe/zi...')
#2 {main}
  thrown in /home/felipe/zig/System/NativeQuery/NativeQuery.php on line 19
[Mon Aug 15 23:32:57 2022] 127.0.0.1:45674 [200]: GET / - Uncaught Error: Call to a member function execute() on bool in /home/felipe/zig/System/NativeQuery/NativeQuery.php:19
Stack trace:
#0 /home/felipe/zig/.temps/preenche-codigo-de-barras-nos-produtos.php(20): System\NativeQuery\NativeQuery->query()
#1 /home/felipe/zig/index.php(44): include('/home/felipe/zi...')
#2 {main}
  thrown in /home/felipe/zig/System/NativeQuery/NativeQuery.php on line 19`.

Em um issue aqui vi a recomendação de importar o dump, porém durante a importação obtive o seguinte erro: `ERROR 1273 (HY000) at line 17: Unknown collation: 'utf8mb4_0900_ai_ci'.`. Alterei o tipo da Collation para utf8 no dump (gambiarras hahahah), prossegui com a importação e funcionou, importou o dump.
Porém ainda sigo obtendo o mesmo erro `(unknown cloumn 'codigo'...) `, no navegador e no log da aplicação.

Estou utilizando um Ubuntu Server 20.04, php7.4.30 e algumas extensões do mesmo.

Agradeço qualquer solução desde já.

**Comment by valdiney** [comment]
Iai mano, beleza? Cara, faz o seguinte, vai na tabela produto e cria um campo chamado (codigo) do tipo int tamanho 10 e not null
e tenta novamente pra ver se vai continuar o erro!

**Comment by itsfks** [comment]
Opa amigo, tudo bem?
Após adicionar a coluna o sistema carregou e deu boa!

Agora preciso apenas do usuário, vi em um outro issue, irei tentar criar uma linha.
Qualquer dica, agradeço!

E muito obrigado pela solução do problema principal.

**Comment by itsfks** [comment]
Como não havia usuário no banco de dados gerado pela aplicação, importei o dump em um novo banco de dados para teste.
Fiz o recomendado em um outro issue de alterar o hash da senha do admin@admin.com para obter acesso, consigo logar porém quando entro obtenho esse erro no navegador:


```
Warning: PDO::query(): SQLSTATE[42000]: Syntax error or access violation: 1055 'zig.mpg.legenda' isn't in GROUP BY in /home/felipe/zig_teste/System/NativeQuery/NativeQuery.php on line 16

Fatal error: Uncaught Error: Call to a member function execute() on bool in /home/felipe/zig_teste/System/NativeQuery/NativeQuery.php:19 Stack trace: #0 /home/felipe/zig_teste/App/Repositories/VendasRepository.php(46): System\NativeQuery\NativeQuery->query() #1 /home/felipe/zig_teste/App/Controllers/HomeController.php(69): App\Repositories\VendasRepository->percentualMeiosDePagamento() #2 [internal function]: App\Controllers\HomeController->index() #3 /home/felipe/zig_teste/System/Route/SelectController.php(228): call_user_func() #4 /home/felipe/zig_teste/System/Route/SelectController.php(63): System\Route\SelectController->instantiateController() #5 /home/felipe/zig_teste/routes/routes.php(131): System\Route\SelectController->run() #6 /home/felipe/zig_teste/index.php(48): require_once('/home/felipe/zi...') #7 {main} thrown in /home/felipe/zig_teste/System/NativeQuery/NativeQuery.php on line 19
```

Tem alguma solução conhecida?

**Comment by valdiney** [comment]
Creio que deva ser a versão do seu Mysql, tenta rodar este comando ai no seu banco e executa a aplicação novamente.
 SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
 
 http://johnemb.blogspot.com/2014/09/adding-or-removing-individual-sql-modes.html

**Comment by itsfks** [comment]
Estou usando o MariaDB na versão 10.3.34 do Ubuntu 20.04.
Não sei se no contexto atual muda algo entre ser o MariaDB ou o MySQL propriamente dito.

Irei rodar esse comando e fazer um teste pela manhã, também tentarei com o próprio MySQL.

Retornarei com os resultados. Muito obrigado novamente!

Enviado do meu iPhone
________________________________
De: Valdiney França ***@***.***>
Enviado: Tuesday, August 16, 2022 10:54:48 PM
Para: valdiney/zig ***@***.***>
Cc: felipe ***@***.***>; Author ***@***.***>
Assunto: Re: [valdiney/zig] Erro durante a instalação. (Issue #136)


Creio que deva ser a versão do seu Mysql, tenta rodar este comando ai no seu banco e executa a aplicação novamente.
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

http://johnemb.blogspot.com/2014/09/adding-or-removing-individual-sql-modes.html

**Comment by itsfks** [comment]
Deu boa! hahahah

Após importar o dump e fazer a inclusão do campo e rodar o comando consegui entrar na home.
Muitíssimo obrigado!

**Comment by itsfks** [comment]
Amigo, seria possível a integração de algum gateway de pagamento como a GerenciaNet?
Ou por exemplo quando gerar uma venda por PIX gerar um PIX QR-Code?

**Comment by valdiney** [comment]
@itsfks na verdade estou com muita vontade de fazer uma integração desse tipo. Mas ainda não tive um tempo de focar para entregar essa integração! Na verdade o sistema está bem simples, quero melhorar bastante coisa nele, mas o intuito é de fato fazer uma integração dessa!

**Comment by itsfks** [comment]
Seria incrível!

Quando eu tiver um tempo irei tentar implementar uma API de código aberto que gera código QR pra PIX, se tudo correr bem eu mando o resultado aqui.

**Comment by valdiney** [comment]
Muito bom mano! Assim que sobrar um tempinho, eu vou adicionar algumas funcionalidades que já tenho na lista!

**Comment by itsfks** [comment]
Opa Valdiney, blz?
Teria alguma forma de não permitir o acesso ao .env via web?

Tentei bloquear no .htaccess e não tive exito

**Comment by valdiney** [comment]
@itsfks Puts, isso é falha brutal de segurança!

**Comment by valdiney** [comment]
@itsfks amanhã eu darei uma olhada nisso e levantarei uma solução! Obrigado por reportar o erro!

**Comment by valdiney** [comment]
Inicialmente da uma olhada: 
https://www.youtube.com/watch?v=8F8MGvXI4Xw

**Comment by itsfks** [comment]
Agradeço amigo. Encontrei meu erro, estava tentando só com <Files /.env>.
