### ISSUE TITLE
PRODUTO NÃO CARREGA

### ISSUE THREAD

**Issue by xiuris** [valdiney/zig#138]
Olá, estou com uma dúvida, a instalação deu certo, não me retorna erros, tive que fazer alguns ajuste na importação do BD, para que a versão mais recente reconhecesse, mas não me retorna erro, os produtos não carrega...

![image](https://user-images.githubusercontent.com/62359678/189795625-74fab393-b399-4f4d-a92f-4b64586a60e0.png)

**Comment by tadeubdev** [comment]
opa! consegue me dizer se aparece algum erro no console do navegador? dá um CTRL + SHIFT + I pra abrir o console e verifica, por favor...

**Comment by xiuris** [comment]
![image](https://user-images.githubusercontent.com/62359678/190047324-173df91c-f989-46a2-812a-3cd0c957a571.png)

**Comment by tadeubdev** [comment]
O sistema está rodando dentro do diretório "vendas"?

**Comment by xiuris** [comment]
isso mesmo!

**Comment by tadeubdev** [comment]
eu vou fazer uns testes e te retorno aqui...

**Comment by tadeubdev** [comment]
Acabei de subir uma correção, quando puder dê um "git pull" pra baixar as atualizações mais recentes ou então baixei o projeto novamente, e me diga se resolveu, por favor. :)
