### ISSUE TITLE
[stories] Correções e melhorias simples

### ISSUE THREAD

**Issue by enriquegeorg** [valdiney/zig#24]
- [x] Função de desativar item (tela de produtos) não esta presente
- [x] Contagem de produtos / clientes desativados (tela home) esta incorreta
- [x] Transformar os menus do pdv diferencial em verticais 
- [x] Adicionar botão de limpar items do pedido (tanto p pdv quanto para pedidos)
- [x] O relatório de período apresenta preço, quantidade e valor total, mas não apresenta os itens vendidos, avaliar colocar os itens do pedido. (talvez colocar um array com os nomes separados por vírgula e tornar o campo expansível ou com tooltip para ver todos os itens)
- [x]  Inserir uma função "desativar usuário" também para os usuários do sistema, e ao fazer, suprimi-lo da lista de vendedores / filtros

**Comment by tadeubdev** [comment]
@enriquegeorg , o que seria essa tarefa?

- Transformar os menus do pdv diferencial em verticais
