### ISSUE TITLE
Adicionar verificação de login

### ISSUE THREAD

**Issue by tadeubdev** [valdiney/zig#33]
Quando se está logado e vai para a base do site, ele não deveria mostrar a página de login. Deveria ser redirecionado para a home.

**Comment by valdiney** [comment]
Feito! Foi adicionado o método logged em LoggedRule e chamado no construtor do Controller de Login!
![image](https://user-images.githubusercontent.com/3947490/86534215-0a523200-bead-11ea-8f6d-8df6c8bb2b87.png)
