### ISSUE TITLE
Criar níveis de acesso de usuários 

### ISSUE THREAD

**Issue by tadeubdev** [valdiney/zig#38]
Atualmente o sistema só conta com o administrador, mas o mesmo poderia adicionar algum vendedor, gerente etc. 
Seria uma boa ter diferentes níveis de acesso para o sistema.

**Comment by valdiney** [comment]
Na verdade estou trabalhando neste modulo. Atualmente temos Super admin, admin e vendedor! Sendo que as permissões são dadas por módulos. Sendo elas: Consultar, criar, editar e excluir! 
Super admin é o responsável pelo sistema, é ele quem pode criar varias empresas que vão utilizar o sistema. Admin são os administradores da empresa, são eles que criam usuários e dá permissões... 

Só para descrever a rotina, seria assim por exemplo! Você baixa o sistema e coloca em algum servidor, você será o super admin, mas como o sistema é multe empresas, você pode cadastrar quantas empresas quiser! Imagine, Hamburguerias, pizzarias...

**Comment by valdiney** [comment]
![image](https://user-images.githubusercontent.com/3947490/86503168-aaab3800-bd81-11ea-8b96-324a776fc39c.png)
Se você for em usuários, tem uma opção no submenu de edição chamado (Permissões) Já é possivel setar os módulos que cada usuário pode acessar! Falta alguns ajustes...

**Comment by tadeubdev** [comment]
Muito bom!
