### ISSUE TITLE
Erro em testes feitos na Hospedagem

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#41]
Localmente funciona, porém na hospedagem deu erro ao tentar fazer login! Tenho que modificar alguma coisa no php.ini?
http://tonie.com.br

@tadeubarbosa 
![image](https://user-images.githubusercontent.com/3947490/86540855-43ef6100-bede-11ea-933f-6e7723e231c4.png)

**Comment by tadeubdev** [comment]
o erro continua?

**Comment by tadeubdev** [comment]
acho que o problema é esse underline aqui...
https://github.com/valdiney/zig/blob/master/System/Session/Session.php#L39

coloca com hífen "zig-" e testa no servidor, por favor.

**Comment by valdiney** [comment]
Tentei aqui, mas não der certo não! A maioria dos erros continuam!

**Comment by tadeubdev** [comment]
ok, mais tarde vou dar uma olhada melhor.

**Comment by tadeubdev** [comment]
estou subindo uma correção daqui a pouco

**Comment by tadeubdev** [comment]
subi uma correção no ultimo pull, quando puder teste por favor
