### ISSUE TITLE
Problema encontrado na rota

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#43]
Exemplo, depois de cadastrar o endereço do cliente, redirecionamos assim.
return $this->get->redirectTo("clienteEndereco", [in64($dados['id_cliente'])]);

o intuito é redirecionar para o método index do controller clienteEndereço mantendo na url o id do cliente.
Porém neste caso a rota não é encontrada, pois não passamos o nome do todo. A rota acha que o id do cliente é o método.

Assim: 
return $this->get->redirectTo("clienteEndereco/index", [in64($dados['id_cliente'])]);

Assim deu erro:
return $this->get->redirectTo("clienteEndereco", [in64($dados['id_cliente'])]); 

Assim funcionou:
return $this->get->redirectTo("clienteEndereco/index", [in64($dados['id_cliente'])]);

**Comment by tadeubdev** [comment]
vou dar uma analisada nisso!

**Comment by tadeubdev** [comment]
Nesse caso a gente verifica a rota como um todo, para isso a gente precisaria de um regex!
Dai verificaríamos a rota clienteEndereco/(.*), entende?
Deixa com o clienteEndereco/index, por enquanto. Essa parte vamos ter que criar, para funcionar com regex.
