### ISSUE TITLE
Erro de session no servidor

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#44]
http://tonie.com.br/

@tadeubarbosa, Essa parte de gerar o id da session não está batendo certo no server não! 

![image](https://user-images.githubusercontent.com/3947490/86990009-086cc500-c172-11ea-8f79-bb0c0017ebd2.png)

**Comment by tadeubdev** [comment]
cara... que engraçado. Mas enfim, vou tirar essa parte de gerar no id, e deixar mais simples. Tô subindo uma atualização daqui a pouco.

**Comment by valdiney** [comment]
Esse é um recurso muito interessante vei! Eu até pesquisei para ver se eu precisava liberar alguma permissão ou configuração no .ini, mas parece que não precisa.

**Comment by tadeubdev** [comment]
sim, eu também achei interessante,  não sei porque não funcionou.
não encontrei nada relacionado no Google.
mas vamos deixar sem isso por enquanto, depois a gente corrige!
