### ISSUE TITLE
Parâmetro opcional na rota é possível? 

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#51]
@tadeubarbosa  é possível passar um parâmetro opcional na rota? Ou seja, um id que eu posso passar ou não! no laravel usa-se algo assim:  {id?}

Quebrou bastante coisas, pois temos rotas onde os parâmetros são opcionais! 
Acho que a gente tem que ver um plano de ação, pois está quebrando muita coisa e estamos somente refatorando. Temos que ter uma primeira versão logo! Acredito que tendo a opção de parâmetro opcional na rota, evita reescrever refatorar até back e front....
![image](https://user-images.githubusercontent.com/3947490/87231020-01b89a80-c38a-11ea-88ba-1c79169d1630.png)

**Comment by tadeubdev** [comment]
Vou dar uma olhada nisso! Não havia me deparado com isso por aqui...
