### ISSUE TITLE
Erro em parâmetros da rota

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#53]
@tadeubarbosa 
Exemplo de rota:
http://localhost:8000/pdvDiferencial/teste/1/2

Dei dois var_dum no método  e retorna:
string(3) "1/2" no primeiro parâmetro concatenou o valor do segundo juntamente com uma barra 
string(0) ""

O correto deveria ser:
string(3) "1"
string(0) "2"

**Comment by tadeubdev** [comment]
cara, que estranho...
ele está atualizado com pull de ontem? acredito que corrigi isso.
até fiz o teste aqui com a mesma rota:

`$route->get('pdvDiferencial/teste/{id?}/{id?}', 'UsuarioController@teste');`
`$route->get('pdvDiferencial/teste/{id}/{id}', 'UsuarioController@teste');`
`$route->get('pdvDiferencial/teste/{any}/{any}', 'UsuarioController@teste');`

`http://zig.local/pdvDiferencial/teste/1/2`
`http://localhost:8000/pdvDiferencial/teste/1/2`

e consegui pegar o 1 e 2:

`string(1) "1"`
`string(1) "2"`

**Comment by valdiney** [comment]
Estranho mesmo vei! Eu acredito que está atualizado porque eu aceitei o pull-request que você havia mandado, mas vou fazer um teste aqui pra ver!

**Comment by valdiney** [comment]
Parcialmente resolvido!
