### ISSUE TITLE
Escolher informações para compor o Dashboard principal da aplicação

### ISSUE THREAD

**Issue by valdiney** [valdiney/zig#6]
- [x] Card (Total das vendas no mês corrente)
- [x] Card (Total das vendas no dia corrente)
- [x] Gráfico tipo Doughnut contendo a porcentagem de vendas por meio de pagamento
- [x] Gráfico tipo Coluna contendo a quantidade de vendas por dia
   
![image](https://user-images.githubusercontent.com/3947490/85203832-b2310280-b2e6-11ea-876d-13cb18dc4adf.png)

**Comment by valdiney** [comment]
![image](https://user-images.githubusercontent.com/3947490/82942013-bb3fe580-9f6d-11ea-9e84-1e8540b2dbb2.png)

**Comment by henrymaltz** [comment]
Vou dar minha sugestão: mostrar o percentual de vendas de cada vendedor, sugiro um gráfico tipo esse que tu fez da forma de pagamento.

**Comment by valdiney** [comment]
Boa @henrymaltz, muito obrigado pela contribuição! Com certeza esse comentário será levado em concideração!

**Comment by tadeubdev** [comment]
essas ideias foram adicionadas, vou fechar a issue por enquanto, depois quando formos discutir o novo dashboard a gente volta ou abre outro
