### ISSUE TITLE
Login Padrão

### ISSUE THREAD

**Issue by Shinglingbr** [valdiney/zig#83]
Olá a todos. Desculpe a ignorância, sou novo na área de programação e estou aprendendo.
Consegui colocar o sistema ON, porem os dados de login informado na documentação nao está logando.

Talvez deve ser algo simples, podem me ajudar por favor?

**Comment by valdiney** [comment]
Olá tudo bem? Tu rodou os comandos de migrations ou você usou o dump do banco?

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus projetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no Medium<https://medium.com/@valdiney> )



________________________________
De: Shinglingbr <notifications@github.com>
Enviado: sexta-feira, 18 de dezembro de 2020 23:49
Para: valdiney/zig <zig@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [valdiney/zig] Login Padrão (#83)


Olá a todos. Desculpe a ignorância, sou novo na área de programação e estou aprendendo.
Consegui colocar o sistema ON, porem os dados de login informado na documentação nao está logando.

Talvez deve ser algo simples, podem me ajudar por favor?

**Comment by Shinglingbr** [comment]
Eu entrei na pasta aonde estão todos os arquivos e executei o comando: php command migrate
Segue print do resultado.
![10 0 0 90 (ZigMoney)](https://user-images.githubusercontent.com/52264003/102679257-1bf27200-418d-11eb-9c7b-4f700654dab6.jpg)

**Comment by valdiney** [comment]
Cara, creio que esquecemos de atualizar essas migrations. Está até faltando algumas tabelas ai pelo que  estou vendo!
No momento, faz o seguinte! Faz um git pull da master ai. Depois vc pega o dump que está na pasta dump e usa ele no seu banco de dados!

Valdiney França:
Programador, instrutor de Computação e desenvolvimento de Software.
( Visualize meu Currículo Online<https://github.com/valdiney/Meu_curriculo> )
( Visualize meus projetos no GitHub<https://github.com/valdiney> )
( Minhas postagens no Medium<https://medium.com/@valdiney> )



________________________________
De: Shinglingbr <notifications@github.com>
Enviado: sábado, 19 de dezembro de 2020 00:00
Para: valdiney/zig <zig@noreply.github.com>
Cc: Valdiney França <valdiney.2@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [valdiney/zig] Login Padrão (#83)


Eu entrei na pasta aonde estão todos os arquivos e executei o comando: php command migrate
Segue print do resultado.
[10 0 0 90 (ZigMoney)]<https://user-images.githubusercontent.com/52264003/102679257-1bf27200-418d-11eb-9c7b-4f700654dab6.jpg>

**Comment by Shinglingbr** [comment]
Valdiney,
Farei isso, posto amanhã o resultado.
Muito obrigado pelas rápidas respostas. Vc é fera!

**Comment by tadeubdev** [comment]
opa! tranquilo, @Shinglingbr ? 
você conseguiu configurar o banco?

**Comment by Shinglingbr** [comment]
Bom dia @tadeubarbosa, eu segui as orientações do nosso amigo @valdiney , porem não consegui. Fiz algo errado com certeza. Por conta do final de semana e trabalho não conseguir mexer mais. Continuarei hj a noite. Posto o resultado caso solucione.

**Comment by Shinglingbr** [comment]
Boa noite nobres colegas!
Após mais uma tentativa, não consegui fazer o sistema funcionar.
Alterei toda estrutura de diversas tabelas nos arquivos de migração. Tomei como base o arquivo dump.sql, da pasta /dump/, e alterei todos arquivos da pasta Database/migrations/....sql.

![image](https://user-images.githubusercontent.com/52264003/102948683-3a19e400-44a5-11eb-93f9-87f4c814ad60.png)

Notei tbm que falta alguns arquivos para criar algumas tabelas que são: pedidos, produtos pedidos e situações pedidos.

Após essa alteração o sistema parece receber o login, mas não consegue retornar a página /login/logar 

![image](https://user-images.githubusercontent.com/52264003/102948768-6df50980-44a5-11eb-98ff-915edda57ad3.png)
![image](https://user-images.githubusercontent.com/52264003/102948959-de9c2600-44a5-11eb-90f6-999aed6599a4.png)

Uma informação que eu devo registar é que o sistema ZigMoney está rodando em uma máquina virtual com sistema Debian 10. Estou acessando a página por IP da rede interna. Caso a estrutura do sistema do sistema ZigMoney seja feita para trabalhar apenas em localhost, por favor me informe. Estou iniciando o PHP com o IP da rede interna, exemplo: php -S 10.0.0.90:8000.

Agradeço toda atenção.

**Comment by DanielGomeX** [comment]
Resolvi este problema ajustando a linha 145 no GetRoute.php em System->Route
Ficando assim:
$baseUrl = "{$protocol}://{$_SERVER['HTTP_HOST']}"."/"."{$branch}";

**Comment by valdiney** [comment]
@Shinglingbr realmente este problema que você está passando é estranho! Ainda não passei por isso! Já testamos o zig em hospedagens como amazon e até mesmo hospedagens compartilhadas! Infelizmente não estou podendo dar uma atenção maior esses dias por conta das demandas de fim de ano! Mas espero ter logo folego para juntos evoluirmos o sistema!

**Comment by tadeubdev** [comment]
Eu subi commit com essa alteração que o @DanielGomeX comentou.
Dá um pull e me diga se resolve o problema, por favor.

**Comment by tadeubdev** [comment]
e aí, @Shinglingbr ! 
vou fechar essa issue porque acho que o problema com as rotas e com as migrations foram corrigidas nos últimos commits... se tiver um outro problema aí fique a vontade para abrir uma nova issue! ;D
